### ISSUE TITLE
Expose port for Apache

### ISSUE THREAD

**Issue by hoeghh** [Praqma/CENTOS-MultiTool#1]
Should we expose port 80 in the Docker file? 

This way we can hit the webserver in a normal docker env. from the host.

**Comment by KamranAzeem** [comment]
Sure! I was also wondering what was the problem when I exposed this
deployment as a service, and it did not work  . Now you made it clear !!!!!
Thanks a lot!!!!

**Comment by KamranAzeem** [comment]
Port 80 and 443 exposed in Dockerfile. Thanks!
